"""empty message

Revision ID: bb5843e30cd8
Revises: 9b0a527981a5
Create Date: 2019-10-18 10:45:19.880296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb5843e30cd8'
down_revision = '9b0a527981a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('telephone', sa.String(length=11), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'telephone')
    # ### end Alembic commands ###
